
import { GoogleGenAI, Type, GenerateContentResponse } from "@google/genai";
import { FurnitureAnalysis } from "../types";

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    // 允许 API Key 为空，避免前端初始化直接崩溃
    // 如果没有 Key，将在实际调用 API 时报错，或者使用 Mock 数据
    // 注意：Vite 要求环境变量必须以 VITE_ 开头才能在客户端访问
    const apiKey = import.meta.env.VITE_GEMINI_API_KEY || import.meta.env.GEMINI_API_KEY || 'PLACEHOLDER_KEY';
    this.ai = new GoogleGenAI({ apiKey });
  }

  async analyzeFurniture(base64Image: string): Promise<FurnitureAnalysis> {
    try {
      const response = await this.ai.models.generateContent({
        model: "gemini-2.0-flash-exp",
        contents: {
          parts: [
            {
              inlineData: {
                data: base64Image.split(',')[1],
                mimeType: 'image/png',
              },
            },
            {
              text: `Analyze this image and identify the main piece of furniture. Return ONLY a JSON object with properties: "type" (short name like 'Sofa', 'Cabinet'), "material" (predominant material), and "description" (a brief 1-sentence physical description).`,
            },
          ],
        },
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              type: { type: Type.STRING },
              material: { type: Type.STRING },
              description: { type: Type.STRING },
            },
            required: ["type", "material", "description"]
          }
        }
      });

      return JSON.parse(response.text || '{}') as FurnitureAnalysis;
    } catch (err) {
      console.warn("API limit reached, using fallback mock data for testing");
      // Fallback Mock Data
      return {
        type: "模拟家具(API超限)",
        material: "默认材质",
        description: "由于API配额限制，这是模拟的识别结果，您可以继续测试改色流程。"
      };
    }
  }

  async listModels() {
    try {
      const response = await this.ai.models.list();
      const models: any[] = [];
      // @ts-ignore
      for await (const model of response) {
        models.push(model);
      }
      console.log("All Available Models List:", models);
      
      // Filter image generation models
      const imageModels = models.filter(m => 
        m.name.includes('image') || 
        m.supportedGenerationMethods?.includes('generateImage') ||
        m.supportedGenerationMethods?.includes('image')
      );
      console.log("Image Gen Models:", imageModels);
      
      return models;
    } catch (error) {
      console.error("Failed to list models:", error);
      return null;
    }
  }

  async editFurnitureColor(
    base64Image: string,
    furnitureType: string,
    colorAndTexture: string,
    hex: string
  ): Promise<string> {
    const response = await this.ai.models.generateContent({
      model: 'imagen-3.0-generate-001',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image.split(',')[1],
              mimeType: 'image/png',
            },
          },
          {
            text: `Professional Interior Re-coloring Task:
            Re-color the primary ${furnitureType} in this image to apply the following product finish: "${colorAndTexture}" (Target Hex: ${hex}).
            
            STRICT CONSTRAINTS:
            1. ONLY re-color the body of the ${furnitureType}.
            2. If the series is "木纹", apply realistic wood grain texture.
            3. If the series is "大理石纹", apply realistic marble veins.
            4. If the series is "金属", apply a subtle metallic sheen with reflections.
            5. If the series is "肤感", apply a smooth, non-reflective ultra-matte finish.
            6. KEEP EVERYTHING ELSE UNCHANGED: The floor, walls, lighting, soft decorations (pillows, lamps, plants), and room layout must remain EXACTLY as they are in the original photo.
            7. Ensure high physical accuracy in how the new material interacts with the existing room lighting.`,
          },
        ],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image generated by the AI");
  }
}

export const geminiService = new GeminiService();
